# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2026-03-23T06:00:14+00:00

from __future__ import annotations

from typing import Any, Dict, List, Literal, Optional, TypedDict, Union

from typing_extensions import NotRequired, TypeAlias

AdjustType: TypeAlias = Literal[
    "forward", "backward", "forward_additive", "backward_additive", "none"
]


class ApiError(TypedDict):
    code: str
    details: NotRequired[Any]
    message: str


class BalanceSheetRecord(TypedDict):
    accounts_payable: NotRequired[Optional[float]]
    accounts_receivable: NotRequired[Optional[float]]
    announce_date: NotRequired[Optional[str]]
    cash_and_equivalents: NotRequired[Optional[float]]
    equity_attributable: NotRequired[Optional[float]]
    fixed_assets: NotRequired[Optional[float]]
    goodwill: NotRequired[Optional[float]]
    intangible_assets: NotRequired[Optional[float]]
    inventory: NotRequired[Optional[float]]
    long_term_borrowing: NotRequired[Optional[float]]
    minority_interest: NotRequired[Optional[float]]
    period_end: str
    retained_earnings: NotRequired[Optional[float]]
    short_term_borrowing: NotRequired[Optional[float]]
    total_assets: NotRequired[Optional[float]]
    total_current_assets: NotRequired[Optional[float]]
    total_current_liabilities: NotRequired[Optional[float]]
    total_equity: NotRequired[Optional[float]]
    total_liabilities: NotRequired[Optional[float]]
    total_non_current_assets: NotRequired[Optional[float]]
    total_non_current_liabilities: NotRequired[Optional[float]]


class BalanceSheetResponse(TypedDict):
    data: Dict[str, List[BalanceSheetRecord]]


class BidAsk(TypedDict):
    ask_prices: List[float]
    ask_volumes: List[int]
    bid_prices: List[float]
    bid_volumes: List[int]


class CashFlowRecord(TypedDict):
    announce_date: NotRequired[Optional[str]]
    capex: NotRequired[Optional[float]]
    net_cash_change: NotRequired[Optional[float]]
    net_financing_cash_flow: NotRequired[Optional[float]]
    net_investing_cash_flow: NotRequired[Optional[float]]
    net_operating_cash_flow: NotRequired[Optional[float]]
    period_end: str


class CashFlowResponse(TypedDict):
    data: Dict[str, List[CashFlowRecord]]


class CnEquityInstrumentExt(TypedDict):
    float_shares: NotRequired[Optional[float]]
    limit_down: NotRequired[Optional[float]]
    limit_up: NotRequired[Optional[float]]
    listing_date: NotRequired[Optional[str]]
    name_en: NotRequired[Optional[str]]
    tick_size: NotRequired[Optional[float]]
    total_shares: NotRequired[Optional[float]]


class CnEquityQuoteExt(TypedDict):
    amplitude: NotRequired[Optional[float]]
    change_amount: NotRequired[Optional[float]]
    change_pct: NotRequired[Optional[float]]
    name: NotRequired[Optional[str]]
    turnover_rate: NotRequired[Optional[float]]


class CnFuturesInstrumentExt(TypedDict):
    float_shares: NotRequired[Optional[float]]
    limit_down: NotRequired[Optional[float]]
    limit_up: NotRequired[Optional[float]]
    listing_date: NotRequired[Optional[str]]
    name_en: NotRequired[Optional[str]]
    tick_size: NotRequired[Optional[float]]
    total_shares: NotRequired[Optional[float]]


class CompactKlineData(TypedDict):
    amount: List[float]
    close: List[float]
    high: List[float]
    low: List[float]
    open: List[float]
    open_interest: NotRequired[List[float]]
    prev_close: NotRequired[List[float]]
    settlement_price: NotRequired[List[float]]
    timestamp: List[int]
    volume: List[int]


class ExFactorEntry(TypedDict):
    ex_factor: float
    timestamp: int


class ExFactorsQuery(TypedDict):
    end_time: NotRequired[Optional[int]]
    start_time: NotRequired[Optional[int]]
    symbols: str


class ExFactorsResponse(TypedDict):
    data: Dict[str, List[ExFactorEntry]]


class ExchangeInfo(TypedDict):
    count: int
    exchange: str
    region: str


class ExchangeListResponse(TypedDict):
    data: List[ExchangeInfo]


class FinancialsQuery(TypedDict):
    end_date: NotRequired[Optional[str]]
    latest: NotRequired[Optional[bool]]
    start_date: NotRequired[Optional[str]]
    symbols: str


class HkEquityInstrumentExt(TypedDict):
    float_shares: NotRequired[Optional[float]]
    lot_size: NotRequired[Optional[int]]
    total_shares: NotRequired[Optional[float]]


class HkEquityQuoteExt(TypedDict):
    amplitude: NotRequired[Optional[float]]
    change_amount: NotRequired[Optional[float]]
    change_pct: NotRequired[Optional[float]]
    name: NotRequired[Optional[str]]
    turnover_rate: NotRequired[Optional[float]]


class IncomeRecord(TypedDict):
    admin_expense: NotRequired[Optional[float]]
    announce_date: NotRequired[Optional[str]]
    basic_eps: NotRequired[Optional[float]]
    diluted_eps: NotRequired[Optional[float]]
    financial_expense: NotRequired[Optional[float]]
    income_tax: NotRequired[Optional[float]]
    net_income: NotRequired[Optional[float]]
    net_income_attributable: NotRequired[Optional[float]]
    non_operating_expense: NotRequired[Optional[float]]
    non_operating_income: NotRequired[Optional[float]]
    operating_cost: NotRequired[Optional[float]]
    operating_profit: NotRequired[Optional[float]]
    period_end: str
    rd_expense: NotRequired[Optional[float]]
    revenue: NotRequired[Optional[float]]
    selling_expense: NotRequired[Optional[float]]
    total_profit: NotRequired[Optional[float]]


class IncomeResponse(TypedDict):
    data: Dict[str, List[IncomeRecord]]


class InstrumentExt1(CnEquityInstrumentExt):
    type: Literal["cn_equity"]


class InstrumentExt2(CnFuturesInstrumentExt):
    type: Literal["cn_futures"]


class InstrumentExt4(HkEquityInstrumentExt):
    type: Literal["hk_equity"]


InstrumentType: TypeAlias = Literal[
    "stock", "etf", "index", "bond", "fund", "futures", "options", "other"
]


class InstrumentsQuery(TypedDict):
    symbols: str


class InstrumentsRequest(TypedDict):
    symbols: List[str]


class IntradayBatchResponse(TypedDict):
    data: Dict[str, CompactKlineData]


class IntradayResponse(TypedDict):
    data: CompactKlineData


class Kline(TypedDict):
    amount: NotRequired[float]
    close: float
    high: float
    low: float
    open: float
    open_interest: NotRequired[Optional[float]]
    prev_close: NotRequired[Optional[float]]
    settlement_price: NotRequired[Optional[float]]
    timestamp: int
    volume: int


class KlinesBatchResponse(TypedDict):
    data: Dict[str, CompactKlineData]


class KlinesResponse(TypedDict):
    data: CompactKlineData


MarketType: TypeAlias = Literal["cn_equity", "cn_futures", "us_equity", "hk_equity"]


class MetricsRecord(TypedDict):
    announce_date: NotRequired[Optional[str]]
    bps: NotRequired[Optional[float]]
    debt_to_asset_ratio: NotRequired[Optional[float]]
    eps_basic: NotRequired[Optional[float]]
    eps_diluted: NotRequired[Optional[float]]
    gross_margin: NotRequired[Optional[float]]
    inventory_turnover: NotRequired[Optional[float]]
    net_income_yoy: NotRequired[Optional[float]]
    net_margin: NotRequired[Optional[float]]
    ocfps: NotRequired[Optional[float]]
    operating_cash_to_revenue: NotRequired[Optional[float]]
    period_end: str
    revenue_yoy: NotRequired[Optional[float]]
    roa: NotRequired[Optional[float]]
    roe: NotRequired[Optional[float]]
    roe_diluted: NotRequired[Optional[float]]


class MetricsResponse(TypedDict):
    data: Dict[str, List[MetricsRecord]]


Period: TypeAlias = Literal[
    "1m", "5m", "10m", "15m", "30m", "60m", "1d", "1w", "1M", "1Q", "1Y"
]


class QuoteExtension1(CnEquityQuoteExt):
    type: Literal["cn_equity"]


class QuoteExtension3(HkEquityQuoteExt):
    type: Literal["hk_equity"]


class QuotesQuery(TypedDict):
    symbols: NotRequired[Optional[str]]
    universes: NotRequired[Optional[str]]


class QuotesRequest(TypedDict):
    symbols: NotRequired[List[str]]
    universes: NotRequired[List[str]]


Region: TypeAlias = Literal["CN", "US", "HK"]


SessionStatus: TypeAlias = Literal[
    "pre_market", "regular", "after_hours", "closed", "halted", "lunch_break"
]


class Universe(TypedDict):
    category: str
    description: NotRequired[Optional[str]]
    id: str
    name: str
    region: str
    symbols: List[str]


class UniverseBatchRequest(TypedDict):
    ids: List[str]


class UniverseSummary(TypedDict):
    category: str
    description: NotRequired[Optional[str]]
    id: str
    name: str
    region: str
    symbol_count: int


class UsEquityInstrumentExt(TypedDict):
    float_shares: NotRequired[Optional[float]]
    total_shares: NotRequired[Optional[float]]


class UsEquityQuoteExt(TypedDict):
    amplitude: NotRequired[Optional[float]]
    change_amount: NotRequired[Optional[float]]
    change_pct: NotRequired[Optional[float]]
    name: NotRequired[Optional[str]]
    turnover_rate: NotRequired[Optional[float]]


class ExchangeInstrumentsQuery(TypedDict):
    type: NotRequired[Optional[InstrumentType]]


class InstrumentExt3(UsEquityInstrumentExt):
    type: Literal["us_equity"]


InstrumentExt: TypeAlias = Union[
    InstrumentExt1, InstrumentExt2, InstrumentExt3, InstrumentExt4
]


class IntradayBatchQuery(TypedDict):
    count: NotRequired[Optional[int]]
    period: NotRequired[Period]
    symbols: str


class IntradayQuery(TypedDict):
    count: NotRequired[Optional[int]]
    period: NotRequired[Period]
    symbol: str


class KlinesBatchQuery(TypedDict):
    adjust: NotRequired[AdjustType]
    count: NotRequired[int]
    end_time: NotRequired[Optional[int]]
    period: NotRequired[Period]
    start_time: NotRequired[Optional[int]]
    symbols: str


class KlinesQuery(TypedDict):
    adjust: NotRequired[AdjustType]
    count: NotRequired[int]
    end_time: NotRequired[Optional[int]]
    period: NotRequired[Period]
    start_time: NotRequired[Optional[int]]
    symbol: str


class QuoteExtension2(UsEquityQuoteExt):
    type: Literal["us_equity"]


QuoteExtension: TypeAlias = Union[QuoteExtension1, QuoteExtension2, QuoteExtension3]


class UniverseDetail(UniverseSummary):
    symbols: List[str]


class UniverseDetailResponse(TypedDict):
    data: UniverseDetail


class UniverseListResponse(TypedDict):
    data: List[UniverseSummary]


class Instrument(TypedDict):
    code: str
    exchange: str
    ext: NotRequired[Optional[InstrumentExt]]
    name: NotRequired[Optional[str]]
    region: str
    symbol: str
    type: NotRequired[Optional[InstrumentType]]


class InstrumentsResponse(TypedDict):
    data: List[Instrument]


class Quote(TypedDict):
    amount: float
    ext: NotRequired[Optional[QuoteExtension]]
    high: float
    last_price: float
    low: float
    open: float
    prev_close: float
    region: Region
    session: NotRequired[Optional[SessionStatus]]
    symbol: str
    timestamp: int
    volume: int


class QuotesResponse(TypedDict):
    data: List[Quote]


class UniverseBatchResponse(TypedDict):
    data: Dict[str, UniverseDetail]


class ExchangeInstrumentsResponse(TypedDict):
    count: int
    data: List[Instrument]
    exchange: str
